### PR TITLE
Search bar changes for #78

### PR DESCRIPTION
**Pull request by racingcow**

### CODE REVIEW

**Comment by wesgate** [comment]
@racingcow - I think all of this looks awesome man. One thing I was hoping we could do would be to hide the initial list when someone clicks the search bar but there is nothing typed into search yet. Essentially not showing the suggestions below until someone types at least one character. Does that make sense?

**Comment by racingcow** [comment]
@wesgate ,

It looks like that `vue-select` control [doesn't support it](https://github.com/sagalbot/vue-select/issues/108). I'll look at switching to `vue-autosuggest`, which should give the [better functionality](https://darrenjennings.github.io/vue-autosuggest/).

**Comment by racingcow** [comment]
Okay @wesgate ,

I think the switch over to `vue-autosuggest` is nearly ready to go. You might want to check my styling, but I think the functionality is there. Let me know if you see anything out of place, or additional changes you'd like to see on this one.

**Comment by wesgate** [comment]
@racingcow 

Looks good man. I merged this into master. You can see I made a couple of commits in addition to what you have. Basically, i am resetting the autosuggest values when the text in the input goes back to '' and then only displaying the autosuggest dropdown when the array has at 1 result. I also went in and set the v-model to filterInput on the autosuggest component so that when you you go to something like /media?tag=Faith, it will prefill the box with 'Faith'

You may want to double-check me to make sure I am doing everything correctly there. I tested it and it seemed to be working well, but feel free to fix anything you see that I missed. You will want to grab the latest from master to see my changes

Thanks!

Wes

**Pull request merged**
